.TH configure-cups "8" "January 2015" "configure-cups" "System Administration Commands (8)"
.SH NAME
configure-cups - starts CUPS and invokes its configuration webinterface
.SH SYNOPSIS
.B configure-cups
.SH DESCRIPTION
`configure-cups', is a small helper tool which starts the Common Unix Printing
System (CUPS) and then invokes x-www-browser to configure the printers used by
it.
.SH AUTHOR
This manual has been written by Stefan Lippers-Hollmann <s.l-h@gmx.de> for 
the Debian project (but may be used by others).
